"""empty message

Revision ID: 0ff339501925
Revises: 7505971ba6f6
Create Date: 2018-05-21 19:19:01.560749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff339501925'
down_revision = '7505971ba6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tracking_device', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    with op.batch_alter_table("tracking_device") as batch_op:
        # batch_op.drop_constraint('tracking_status', type_='foreignkey')
        batch_op.create_foreign_key('tracking_status', 'tracking_device', ['tracking_device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracking_status', type_='foreignkey')
    op.create_foreign_key(None, 'tracking_status', 'product', ['date_recordered'], ['id'])
    op.drop_column('tracking_device', 'token_expiration')
    # ### end Alembic commands ###
