"""empty message

Revision ID: 7505971ba6f6
Revises: 36b3ff45f5b8
Create Date: 2018-05-21 17:56:22.017533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7505971ba6f6'
down_revision = '36b3ff45f5b8'
branch_labels = None
depends_on = None


def upgrade():
    return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking_status', sa.Column('tracking_device_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'tracking_status', type_='foreignkey')
    op.create_foreign_key(None, 'tracking_status', 'tracking_device', ['tracking_device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracking_status', type_='foreignkey')
    op.create_foreign_key(None, 'tracking_status', 'product', ['date_recordered'], ['id'])
    op.drop_column('tracking_status', 'tracking_device_id')
    # ### end Alembic commands ###
