"""empty message

Revision ID: 76bd7aab09f1
Revises: 8636ec2b99a8
Create Date: 2018-05-20 20:45:36.171874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76bd7aab09f1'
down_revision = '8636ec2b99a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('disabled',
                   existing_type=sa.BOOLEAN())
        batch_op.drop_column('active')
    with op.batch_alter_table('organization') as batch_op:
        batch_op.alter_column('disabled',
                   existing_type=sa.BOOLEAN())
        batch_op.drop_column('active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.alter_column('user', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('organization', sa.Column('active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
