"""empty message

Revision ID: 8636ec2b99a8
Revises: aa6e785a1eba
Create Date: 2018-05-20 20:43:08.753096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8636ec2b99a8'
down_revision = 'aa6e785a1eba'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('organization', 'active')
    #op.drop_column('user', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.add_column('organization', sa.Column('active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
