"""empty message

Revision ID: 8c9145814fb7
Revises: 5b48190171de
Create Date: 2018-05-21 16:53:32.649384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9145814fb7'
down_revision = '5b48190171de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('status', sa.String(length=120), nullable=True))
    op.add_column('tracking_status', sa.Column('tracking_device_id', sa.Integer(), nullable=True))
    # with op.batch_alter_table('tracking_status') as batch_op:
        # batch_op.create_foreign_key('tracking_device', ['tracking_device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracking_status', type_='foreignkey')
    op.create_foreign_key(None, 'tracking_status', 'product', ['date_recordered'], ['id'])
    op.drop_column('tracking_status', 'tracking_device_id')
    op.drop_column('product', 'status')
    op.drop_column('product', 'date_created')
    # ### end Alembic commands ###
