"""empty message

Revision ID: aa6e785a1eba
Revises: 86087e1ad0b0
Create Date: 2018-05-20 20:40:02.838793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6e785a1eba'
down_revision = '86087e1ad0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.drop_column('organization', 'active')
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.drop_column('user', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'disabled')
    op.add_column('organization', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.drop_column('organization', 'disabled')
    # ### end Alembic commands ###
