"""empty message

Revision ID: c7023a27bed4
Revises: 76bd7aab09f1
Create Date: 2018-05-20 23:57:28.204672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7023a27bed4'
down_revision = '76bd7aab09f1'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_types', sa.Column('expiration_date_length_hours', sa.Integer(), nullable=True))
    # op.drop_column('product_types', 'expiration_date_length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_types', sa.Column('expiration_date_length', sa.DATETIME(), nullable=True))
    op.drop_column('product_types', 'expiration_date_length_hours')
    # ### end Alembic commands ###
