"""empty message

Revision ID: ddfdd49dfb19
Revises: 0ff339501925
Create Date: 2018-05-21 19:26:14.848695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfdd49dfb19'
down_revision = '0ff339501925'
branch_labels = None
depends_on = None


def upgrade():
    return
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table("tracking_status") as batch_op:
        #batch_op.drop_constraint('date_recordered', type_='foreignkey')
        #batch_op.create_foreign_key('tracking_status', 'tracking_device', ['tracking_device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracking_status', type_='foreignkey')
    op.create_foreign_key(None, 'tracking_status', 'product', ['date_recordered'], ['id'])
    # ### end Alembic commands ###
